name: using env vars
on: 
  workflow_dispatch:
    inputs:
      name:
        description: 'The name of the variable'
        required: true
        default: 'this is workflow variable'
      address:
        description: 'The address of the user'
        required: true
        default: '24'

jobs:
  job1:
    name: this is job1
    runs-on: ubuntu-latest
    steps:
      - run: echo "This is global variable ${{github.events.input.name}}"
      - run: echo "This is Job variable ${{github.event.input.address}}"
      - run: echo "This is run/step variable ${{env.VAR1}}-3"
