name: using env vars
on: 
  workflow_dispatch:
    inputs:
      env:
        description: 'Environment Name- DEV/TEST/STAGE/PREPROD/PROD'
        default: 'DEV'
        required: true
jobs:
  job1:
    name: this is job1
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello ${{secrets.NAME}}"
      - run: echo "Bye ${{secrets.NAME}}"
      - run: echo "This is run/step variable ${{env.VAR1}}-3"
