name: using env vars
on: workflow_dispatch
env:
  VAR1: BRAD
jobs:
  job1:
    name: this is job1
    runs-on: ubuntu-latest
    steps:
      - run: echo "This is global variable ${{ env.VAR1}}"
      - run: echo "This is Job variable ${{env.VAR1}}-2"
      - run: echo "This is run/step variable ${{env.VAR1}}-3"
