name: Manual Workflow
#########define workflow #######
on: workflow_dispatch
#############define jobs to execute######
jobs:
########setup steps for a job#####
  my_first_job:
    name: My first job
    #########setup a runner####
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello world"
##########run a command or use actions######
  my_second_job:
    name: My second Job
    runs-on: ubuntu-latest
    steps:
      - run: echo "bye world"